### ISSUE TITLE
BUG: Fog effects do not render in ezquake 3.6

### ISSUE THREAD

**Issue by ginzberg** [QW-Group/ezquake-source#578]
**ezQuake version:**
Affected: `3.6-dev-alpha9-dev r7137~488ac9da`
Baseline for comparison: `3.2-dev r5245~658f2b8d`

**OS/device including version:**
OS: Linux (5.13.12-zen1-1-zen kernel)
GPU: Nvidia 3080 - driver 470.63.01
Renderer: Both `vid_renderer 0` and `vid_renderer 1` are equally effected

**Describe the bug**
`gl_fog 1` has no effect

**To Reproduce**
1. Open ezquake 3.2
2. Set the following:
   - `gl_fog "1"`
   - `gl_fogend "2000"`
   - `gl_fogstart "400"`
   - be sure to `vid_restart`
3. Go to the top of dm6 and look from cells towards nailgun
4. Observe that the fog is rendered as the view distance increases (e.g. works as intended)

Now, repeat these steps in 3.6:
1. Open ezquake 3.6
2. Set the following:
   - `vid_renderer "0"`
   - `gl_fog "1"`
   - `gl_fogend "2000"`
   - `gl_fogstart "400"`
   - be sure to `vid_restart`
3. Go to the top of dm6 and look from cells towards nailgun
4. Observe that the fog is not rendered
5. Set the following: 
  - `vid_renderer "1"`
  - `gl_fog "1"`
  - `gl_fogend "2000"`
  - `gl_fogstart "400"`
  - be sure to `/vid_restart`
6. Go to the top of dm6 and look from cells towards nailgun
4. Observe that the fog is not rendered

**Expected behavior**
The fog should render as expected from the commands, as it does in the prior 3.2 version of ezQuake.

**Screenshots**
Also please attach your config (.cfg) file

Expected behavior (as seen from ezQuake 3.2)
![ezquake000](https://user-images.githubusercontent.com/775372/130354040-7e93fc32-55c9-46fe-9542-bd8f392d7a51.png)

Observed behavior (as seen from ezQuake 3.6)
![ezquake001](https://user-images.githubusercontent.com/775372/130354048-4e6be073-b7b6-4e9a-af82-1842bea64c29.png)

**Comment by meag** [comment]
Hi - this correct, there is no glsl fog at the moment.  If you disable glsl rendering in classic renderer (`/gl_program_xxx`) you'll see the fog return.

I did look at this but got sidetracked trying to work out what Floris/ruwetuin logged these fog-related bugs for on SourceForge... Don't suppose anyone would know if dumping the z-buffer out to disk when taking screenshots/movie serve a better purpose?

https://sourceforge.net/p/ezquake/feature-requests/470/
https://sourceforge.net/p/ezquake/feature-requests/469/
https://sourceforge.net/p/ezquake/bugs/526/

Seems to be an explanation here but I don't know what the movie people use the different captures for: https://www.quakeworld.nu/blog/317/video-ideas#90944

**Comment by ginzberg** [comment]
@meag Ah - that's a great workaround for now. The added benefit is that I can keep gl_program_sky set to 1, and the skyboxes remain while the world has fog. I know this is not as intended, but an interesting side affect.

**Comment by hemostx** [comment]
The depth buffer can be used for a number of tricks, people with a bit of compositing/vfx knowledge would be happy to have it - typically for Depth of Field blur :)
Since you can extract shapes from the data, this means you can mask stuff off easily which enables, for example
- Just plain skipping a "green screen" type of color pass to extract shapes
- Outline effects (*gl_outline without edges from inside the model* ;) )
There are even quick hacks for motion blur and SSAO, although they'd probably require a fair bit of extra offline cleanup .

As TheBeats explains on qw.nu, multiple demo captures don't always line up for some reason, I understand the need to try and get what you want in as few passes as you want. Having the real z-buffer would help a fair bit, but does not cover all cases.

For Floris's case of "particles stay visible when fog is on " this might not be enough depending on when you dump the z-buffer (is it before or after drawing the particles and 2d and and and...). I think Floris needs multiple passes anyway to be able to cleanly separate HUD and particles, including some chroma key pass (=> r_drawflat and/or r_fullbright tricks) - I wouldn't want to track every gib in depth separately in multiple z-masking passes....

**Comment by meag** [comment]
Can you explain what "track every gib in depth separately in multiple z-masking passes" means?  We could export an image with a color for each entity, would that help with tracking?

**Comment by hemostx** [comment]
Don't mind that. I was just trying to find solutions to Floris's bug reports and use cases with the z-buffer. I think what you're asking would be super cool, but if no one's asked for it beyond that one user... they can just work their masks manually like everyone else :]

Essentially, in compositing tools like i.e. Natron (it's free, check it out) or I hope Afteer Effects, there's a z-mask effect.
You feed a it a color channel, a z-buffer and a range of depth, and it extracts a mask in that z range for you. If you consider a fountain of gibs, you get gibs going in opposite directions, and I feel like it would require tracking of individual gibs in different z-mask passes + recombining.
OTOH just using a green screen approach, you could get a mask for all of the gibs at once.

Make sense? :c

**Comment by blaps** [comment]
Raising a voice for such a feature, for film effects, extracting the player moves from the background for example.

**Comment by dsvensson** [comment]
@meag I tried out your work in progress fog commits and perhaps you are aware of it already, but using the `r_fx_fog_usemap` produces fog of the wrong color vs for example FTE. My map has `_fog` set to `0.011 0.9921 0.9843 0.8039` and it produces a turquoiseisch fog. Great to see it happening though!
